apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-content
  namespace: ccnube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-content
  template:
    metadata:
      labels:
        app: be-content
    spec:
      containers:
        - name: be-content
          image: be-content:v1
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 19080
          volumeMounts:
            - name: config-volume
              mountPath: /data/conf
      volumes:
        - name: config-volume
          configMap:
            name: ccnube-config
            items:
              - key: be-content.yaml
                path: config.yaml