server:
  name: "library"
  grpc:
    network: "tcp"
    addr: "0.0.0.0:19093"
    timeout: 20s

data:
  database:
    source: "root:12345678@tcp(ccnubox-mysql:3306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    network: "tcp"
    addr: "ccnubox-redis:6379"
    password: "12345678"
    read_timeout: "3s"
    write_timeout: "3s"

registry:
  etcd:
    addr: "ccnubox-etcd:2379"
    username: "root"
    password: "12345678"
  usersvc: "discovery:///user"

zaplog:
  log_level: "info"
  log_format: "json"
  log_path: "/logs"
  log_file_name: "app.log"
  log_file_max_size: 100
  log_file_max_backups: 30
  log_max_age: 7
  log_compress: false
  log_stdout: true
