log:
  path: "/logs/proxy.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）

shenlongConf:
  api: "http://api.shenlongip.com/ip?key=xxx&protocol=1&mr=1&pattern=txt&count=1&sign=xxxx"
  interval: 100 # 单位: s
  retry: 3
  username: "xxx"
  password: "xxx"


otel:
  serviceName: "be-proxy"
  serviceVersion: "1.0.0"
  endpoint: "localhost:4318"