server:
  http:
    addr: 0.0.0.0:18000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:19083
    timeout: 10s
data:
  es:
    url: "http://127.0.0.1:9200"
    setsniff: false
    username: "elastic"
    password: "12345678"
    #重启后是否保留数据
    keepDataAfterRestart: true
    classroom: "/data/conf/classrooms.json"
  redis:
    addr: "localhost:6379"
    password: "12345678"
  database:
    dsn: "root:12345678@tcp(localhost:13306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"
    data_alive: 1
    log_level: "warn"
    log_file_name: "sql.log"
    log_path: "/logs"
registry:
  etcd:
    addr: "127.0.0.1:2379"
    username: root
    password: "12345678"
  proxysvc: "discovery:///proxy"

## 执行job时使用的学号
proxyStuId: "xxxxxxxxxx"