mysql:
  dsn: "root:12345678@tcp(localhost:13306)/ccnubox?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: "12345678"

etcd:
  endpoints:
    - "localhost:2379"
  username: root
  password: "12345678"

grpc:
  server:
    name: "user"
    weight: 100
    addr: ":19091"
    etcdTTL: 60
  client:
    ccnu:
      endpoint: "discovery:///ccnu"
      retryCnt: 3
    proxy:
      endpoint: "discovery:///proxy"

log:
  path: "/logs/user.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）

otel:
  serviceName: "be-user"
  serviceVersion: "1.0.0"
  endpoint: "localhost:4318"