global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['ccnubox-prometheus:9090']

  - job_name: 'ccnubox'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets:
          - 'bff:8080'
    basic_auth:
      username: "root"
      password: "12345678"

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 'ccnubox-node-exporter:9100'
