#成绩自动提醒
gradeConf:
  high: 15  #单位是分钟
  middle: 30 #单位是分钟
  low: 60 #单位是分钟
  
consumeConf:
  consumeTime: 1 #强制插入的时间(如果长期没有消息被消费的话),单位是分钟
  consumeNum: 100 #批量存入,每次最多一次存入500条数据(设置最大值不能超过一千,否则请自行修改dao层的gorm插入feedEvent的最大上限值)

log:
  path: "/logs/app.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）

otel:
  serviceName: "be-grade"
  serviceVersion: "1.0.0"
  endpoint: "localhost:4318"