calendarController:
  durationTime: 24 #爬取频率,单位是小时

qiniu:
  accessKey : ""#秘钥
  secretKey : ""#秘钥x2
  bucket: "ccnubox"#仓库名
  domain : "http://xxxxx"#默认域名
  baseName : "calendar/"

log:
  path: "/logs/app.log"  # 日志文件路径
  maxSize: 100           # 单个日志文件的最大大小（MB）
  maxBackups: 7          # 保留旧日志文件的最大数量
  maxAge: 30             # 日志文件保留天数
  compress: 1             # 是否压缩旧日志文件（1 表示压缩，0 表示不压缩）

otel:
  serviceName: "be-content"
  serviceVersion: "1.0.0"
  endpoint: "localhost:4318"
